export default {
  translations: {
    btn: '/images/home/zh_CN.png',
    '志多星': '志多星',
    '首页': 'home',
    '个人中心': 'Personal center',
    '获取验证码': 'Get verification code',
    '请输入验证码': '请输入验证码',
    '请输入手机号': 'Please enter your mobile number',
    '手机号或证件号码': 'Mobile number/ID number',
    '输入密码': 'Enter password',
    '忘记密码': 'Forget password',
    '登录': 'Login',
    '图形验证码': 'Captcha',
    '手机验证码': 'Phone verification code',
    '登录/注册': 'Log/Register',
    '提交代表已阅读': 'Submit means that you have read the',
    '用户协议': '"User Agreement"',
    '快速登录': 'Quick login',
    '账号登录': 'Account login',

    '搜索项目/团队': 'Search',
    '搜索项目': 'Search',
    '搜索志愿团队': '搜索志愿团队',
    '全国': 'China',
    '市': 'City',
    '城市': 'City',
    '当前城市': 'Current location',
    '志愿项目': 'Volunteer project',
    '正在加载': 'loading',
    '智能排序': 'Automatic sorting',
    '最新发布': 'Latest release',
    '距离最近': 'Nearest',
    '热门活动': 'Popular activities',
    '服务类型': 'Service type',
    '服务对象': 'Service object',
    '项目日期': 'Project date',
    '招募截止': 'Recruitment deadline',
    '服务时长': 'Service hour',
    '搜索团队': 'Search',
    '团队类型': 'Team type',
    '所在区域': '所在区域',
    '目前还没有您已加入的团队哦': '目前还没有您已加入的团队哦',
    '目前还没有团队哦': '目前还没有团队哦',
    '目前还没有活动哦': '目前还没有活动哦',
    '审核中': '审核中',
    '审核中，请稍后': 'Under review, please wait patiently',
    '时长': 'Volunteer hours',
    '小时': 'H',
    '时': 'H',
    '成员': 'Members',
    '人': '',
    '活动日期': 'Activity date',
    '我的': 'My',
    '星币': 'Scores',
    '明细': '明细',
    '志愿回馈': 'Volunteer rewards',
    '请先登录': '请先登录',
    '兑换记录': 'Redeem record',
    '前往登录': '前往登录',
    '目前还没有订单哦': 'There is no order yet',
    '目前还没有商品哦': 'There are no products yet',
    '元': '元',
    '库存n件': '{{n}} pieces in stock',
    '件': '件',
    '至': '-',
    '发起方': 'Initiator',
    '支持方': '支持方',
    '商品简介': '商品简介',
    '兑换该商品需要消耗n星币，您是否兑换': 'This product requires {{n}} points. Do you confirm the redeem',
    '兑换该商品需要消耗': 'This product requires',
    '您是否兑换吗': 'Do you confirm the redeem',
    '线下兑换日期': 'Product description',
    '已售罄': '已售罄',
    '已达到兑换限制': '已达到兑换限制',
    '返回积分商城首页': 'Return to the homepage of the Mall',
    '兑换失败': 'Redemption failed',
    '兑换成功': 'Redemption succeed',
    '支付金额': 'Pay',
    '积分': 'points',

    '立即兑换': 'Redeem now',
    '确认兑换': 'Confirm',
    '下单时间': 'Order time',
    '兑换时间': '兑换时间',
    '未到兑换日期': '未到兑换日期',
    '确认已兑换': '确认已兑换',
    '兑换失败，商品已过兑换日期（不返还积分）': '兑换失败，商品已过兑换日期（不返还积分）',
    '兑换失败': 'Redemption failed',
    '兑换成功': 'Redemption succeed',
    '确认是否已兑换': '确认是否已兑换',
    '联系人姓名': '联系人姓名',
    '联系人电话': '联系人电话',
    '志愿保障': '志愿保障',
    '退出报名': '退出报名',
    '提示': '提示',
    '登录提示': '登录提示',
    '转发给好友': '转发给好友',
    '分享到朋友圈': '分享到朋友圈',
    '保存海报': '保存海报',
    '您已被添加到黑名单，请联系客服': '您已被添加到黑名单，请联系客服',
    '我要捐款': '我要捐款',
    '我要报名': 'Sign up',
    '已录用人数': 'Number of volunteers recruited',
    '项目介绍': 'Project introduction',
    '暂无介绍': '暂无介绍',
    '收藏': 'Favorites',
    '分享': 'Share',
    '项目详情': 'Project details',
    '项目社区': 'Project community',
    '确定要退出项目吗': '确定要退出项目吗',
    '团队成员(人)': 'Team member(people)',
    '团队总时长(小时)': 'Total volunteer hours of team members(hours)',
    '团队口号': 'Team slogan',
    '团队详情': 'Team details',
    '团队成员': 'Team member',
    '我的收藏': 'My favorites',
    '上级团队': 'Superior team',
    '注册日期': 'Registration date',
    '团队管理': 'Team management',
    '联系电话': 'Contact number',
    '团队地址': 'Team address',
    '团队简介': 'Team Profile',
    '团队项目': 'Team project',
    '团队社区': 'Team community',
    '确定要退出团队吗': 'T确定要退出团队吗',

    // 志愿圈
    '消息列表': 'Message',
    '发布动态': 'Post',
    '还没有动态信息': 'No update yet.',
    '只有登录的用户才能点赞和评论哦～': '只有登录的用户才能点赞和评论哦～',
    '社区互动': '社区互动',
    '请输入评论': '请输入评论',
    '回复': '回复',
    '这一刻的想法': 'Thoughts at this moment (maximum 200 words)',
    '发表': 'Post',
    // 排行榜
    '年度榜': '年度榜',
    '总榜': '总榜',
    '志愿排行': 'Volunteer ranking',
    'Ta的成就': 'Ta的成就',
    '年度时长': '年度时长',
    '总时长': 'Total volunteer hours',
    'Ta的项目': 'Ta的项目',
    '获得': 'Get',
    '已获得时长': '已获得时长',
    'Ta的团队': 'Ta的团队',

    '取消': 'Cancel',
    '确认': 'Confirm',
    '无': '无',
    '删除': 'Delete',
    '选填': 'optional',
    '提交': 'Submit',
    '存在必填项，请完善后重新提交': '存在必填项，请完善后重新提交',

    '已结束': 'Registration is over',
    '我要加入': '我要加入',
    '我要退出': 'I’d like to quit',
    '申请助养': '申请助养',
    '等待审核': '等待审核',
    '项目审核中': '项目审核中',
    '进行中': '进行中',
    '已满员': '已满员',

    '我发现了': 'I found',
    '我参与了': '我参与了',
    '团队': 'team',
    '项目': 'project',
    '累计获得': '累计获得',
    '个服务时长': '个服务时长',
    '跟我一起做志愿服务吧': '这个团队，跟我一起做志愿服务吧',

    // 补卡
    '申请补卡成功': '申请补卡成功',
    '申请服务时长': 'Application for volunteer hours',
    '申请补卡': 'Application after the activity',
    '参加项目': 'Join the project',
    '请选择': 'Please select',
    '参加活动地点': 'Activity location',
    '申请时长(小时)': 'Application hours',
    '申请说明(默认)': 'Application description (within 200 words)',
    '申请说明': 'Application description (within 200 words): Please specify the activity location (name of kindergarten, elementary school, etc.), number of beneficiaries (number of teachers, family members and students), and other relevant information about the activity.',
    '活动证明图片(默认)': 'Activity picture（optional）',
    '活动证明图片': 'Activity picture (such as student sign-in form, activity photo, group photo, etc., required information)',
    '还没有项目可以签到': '还没有项目可以签到',
    '快去加入项目吧': '快去加入项目吧',
    '浏览项目': '浏览项目',
    '近3天待打卡项目': 'Projects to be checked in within three days',
    '签到打卡': 'Check in',
    '所有项目': 'All projects',
    '已进入签到地点范围': '已进入签到地点范围',
    '查看签到地点': '查看签到地点',
    '获取定位失败，请获取定位权限': '获取定位失败，请获取定位权限',
    '定位中...': 'Positioning...',
    '打卡成功': '打卡成功',
    '打卡': 'Check in',
    '签到': 'Check in',
    '时间': '时间',
    '补卡': '补卡',
    '待审': '待审',
    '通过': '通过',
    '驳回': '驳回',
    '打卡开始时间': 'Check-in starting time',
    '打卡截止时间': 'Check-in deadline',
    '签退时间': '签退时间',
    '签退打卡': '签退打卡',
    '重新申请补卡': '重新申请补卡',
    '预计可获得服务时长': 'Estimated volunteer hours',
    '获得服务时长': 'Estimated volunteer hours',
    '预计最多可获得服务时长': 'Estimated maximum volunteer hours',
    '未提审': '未提审',
    '待打卡': '待打卡',
    '已通过': '已通过',
    '审核中': '审核中',
    '被驳回': '被驳回',
    '已签到': '已签到',
    '待补卡': '待补卡',
    '目前还没有班次哟~': 'There are currently no activities that require check-in.',
    '近3天待打卡班次': '近3天待打卡班次',
    '所有班次': 'All activities',


    // 个人中心
    '未设置昵称': '未设置昵称',
    '未设置口号': '未设置口号',
    '我的团队': 'My team',
    '我的项目': 'My project',
    '服务时长(center)': 'Volunteer hour',
    '星币(center)': 'points',
    '志愿': 'Volunteer',
    '个': '',
    '社区友好基金': '社区友好基金',
    '我的志愿圈': 'Moments',
    '我的消息': 'My message',
    '个人资料': 'Personal information',
    '我的证书': 'My volunteer certificate',
    '我的家庭': 'My family',
    '服务中心': 'Service center',
    '平台介绍': 'Platform introduction',
    '使用帮助': 'User help',
    '客服中心': 'Customer service',
    '设置': 'Settings',
    '当前等级': '当前等级',
    '暂无等级': '暂无等级',
    '成长值': '成长值',
    '成长体系': '成长体系',
    '您可以通过更多志愿行为来获得成长值': '您可以通过更多志愿行为来获得成长值',
    '查看': '查看',
    '获取方法': '获取方法',
    '查看成长值获得方法': '查看成长值获得方法',
    '如何获得成长值': '如何获得成长值',
    '支出': '支出',
    '如何获得': '如何获得',
    '下列操作可以帮你获得': '下列操作可以帮你获得',
    '下列操作可以帮你获得成长值': '下列操作可以帮你获得成长值',
    '操作': '操作',
    '获得成长值': '获得成长值',
    '我知道了': '我知道了',  //按钮
    '退出登录': 'Log out',
    '修改密码': 'Revise the password',
    '新密码': 'New password',
    '确认修改': 'Confirm',
    '还没有消息哟': 'You have not received any messages',
    '目前还没有消息': 'You have not received any messages',
    '站内邮箱': '站内邮箱',
    '确认设置': 'Confirm',

    //
    '请填写': '请填写',
    '手机号': 'Mobile number',
    '发送': 'Send',
    '团队密码': 'Password',
    '确认密码': 'Confirm',
    '密码': 'Password',
    '请输入字母数字中文格式昵称': '请输入字母数字中文格式昵称',
    '密码最少6位': '密码最少6位',
    '密码范围6-20位数字字母组成': '密码范围6-20位数字字母组成',
    '请输入合法的邮箱地址': '请输入合法的邮箱地址',
    '请输入正确的用户名': '请输入正确的用户名',
    '同一时间内不能多次点击': '同一时间内不能多次点击',
    '上传头像(选填)': '上传头像(选填)',
    '昵称': '昵称',
    '图片码': '图片码',
    '验证码': '验证码',
    '注册': 'Register',
    '已有账号，前往登录': '已有账号，前往登录',
    '志多星用户协议': '志多星用户协议',
    '全部': 'All',
    '待录用': '待录用',
    '已录用': '已录用',
    '请联系客服电话': 'Please call customer service',
    '确认提交': '确认提交',
    '邮箱': 'E-mail',
    '暂无记录': '暂无记录',


    '关系': 'Relationship',
    '儿子': 'Son',
    '女儿': 'Daughter',
    '丈夫': 'Husband',
    '妻子': 'Wife',
    '母亲': 'Mother',
    '父亲': 'Father',
    '爷爷': 'Grandfather',
    '奶奶': 'Grandmother',
    '其他': 'Other',
    '添加': 'Confirm',
    '新建家庭成员': 'New family member',
    '姓名': 'Name',
    '证件类型': 'Type of certificate',
    '证件号码': 'ID number',
    '性别': 'Gender',
    '民族': 'Ethnicity',
    '现居住地址': 'Current address',
    '省份': 'Province',
    '区县': 'District/county',
    '详细地址': 'Detailed address',
    '街道': '街道',
    '出生日期': 'Date of birth',
    '请选择出生日期': '请选择出生日期',
    '个人信息绑定': '个人信息绑定',
    '员工号有误，请检查': '员工号有误，请检查',
    '修改资料': 'Revise',
    '需要帮助': 'Need help',
    '申请成为实名注册志愿者': '申请成为实名注册志愿者',
    '修改': '修改',
    '确定要修改成员信息吗': '确定要修改成员信息吗',
    '请输入中文姓名或英文姓名': '请输入中文姓名或英文姓名',
    '请输入中文姓名': '请输入中文姓名',
    '身份证输入不合法': '身份证输入不合法',


    '基本信息': 'Basic information',
    '头像': 'Profile',
    '账号': 'Account',
    '志愿者编号': 'Volunteer number',
    '个人擅长': 'Specialty',
    '关爱服务': 'Caring service',
    '国际服务': 'International service',
    '社区服务': 'Community service',
    '应急救援': 'Emergency rescue',
    '赛事服务': 'Tournament service',
    '医疗卫生': 'Medical care',
    '绿色环保': 'Environmental protection',
    '文化倡导': 'Cultural advocacy',
    '教育': 'Education',
    '助残': 'Assistance to the disabled',
    '助老': 'Assistance to the elderly',
    '其他': 'Other',
    '志愿者口号': 'Slogan',
    '保存': 'Save',
    '实名认证信息': 'Real-name authentication information',

    '男': '男',
    '女': '女',
    '未知': '未知',
    '内地居民身份证':	'PRC Resident Identity Card',
    '香港居民身份证': 'Hong Kong Identity Card',
    '澳门居民身份证': 'Macau Identity Card',
    '台湾居民身份证': 'Taiwan Identity Card',
    '护照': 'Passport',

    '添加成员': 'Add family member',
    '绑定家庭成员': 'Bind family member',
    '家庭成员': 'Family member',
    '加载中': '加载中',
    '志愿总时长': '志愿总时长',
    '添加成员说明': 'Note: The added family member can log in with ID number and password',

    '参加的项目': '参加的项目',
    '请选择申请项目': '请选择申请项目',
    '请选择申请班次': '请选择申请班次',
    '请选择补卡时间': '请选择补卡时间',
    '请选择签到时间': '请选择签到时间',
    '请选择签退时间': '请选择签退时间',
    '请输入详细说明': '请输入详细说明',
    '补卡班次': '补卡班次',
    '打卡时间': '打卡时间',
    '签到补卡时间': '签到补卡时间',
    '签退补卡时间': '签退补卡时间',
    '工作证明图片': '工作证明图片',

    // 成就
    '生成图片失败，请重试': '生成图片失败，请重试',
    '累计服务时长': '累计服务时长',
    '次': '',
    '参加': '参加',
    '项目签到打卡': '项目签到打卡',
    '项目累计服务时长': '项目累计服务时长',
    '服务时长已累计超过': '服务时长已累计超过',
    '快去晒成就吧': '快去晒成就吧',
    '签到打卡次数已累计超过': '签到打卡次数已累计超过',
    '参加项目次数已累计超过': '参加项目次数已累计超过',
    '项目签到打卡次数已累计超过': '项目签到打卡次数已累计超过',

    '长按保存图片到手机': 'Long press to save the picture to the phone',
    '长按识别二维码 一起来做志愿者': 'Long press to identify the QR code to be volunteers together',
    '我发现了这个团队，跟我一起做志愿服务吧': 'I found this team, let\'s do volunteer service with me',
  },
}
