export default {
  translations: {
    btn: '/images/home/zh_CN.png',
    '志多星': 'Volstar',
    'BMW企业志愿者协会': 'BMW Corporate Volunteer Association',
    '志多星演示版': 'Volstar Test',

    '首页': 'Home',
    '个人中心': 'Personal center',
    '获取验证码': 'Obtain',
    '验证码获取': 'Obtain',
    '设置密码': 'Set the password',
    '请输入验证码': 'Please enter the verification code',
    '请输入手机号': 'Please enter your mobile number',
    '请先阅读协议':'Please check the consent after reading the user agreement.',
    '手机号或证件号码': 'Mobile number/ID number',
    '输入密码': 'Enter password',
    '忘记密码': 'Forget password',
    '登录': 'Login',
    '图形验证码': 'Captcha',
    '手机验证码': 'Phone verification code',
    '登录/注册': 'Log/Register',
    '已阅读': 'Have read the',
    '提交代表已阅读': 'Submit means that you have read the',
    '用户协议': '"User Agreement"',
    '快速登录': 'Quick login',
    '账号登录': 'Account login',

    '已经成功定位到当前定位城市': 'The current location has been successfully located',
    '定位失败，请确认同意定位授权': 'Positioning failed, please confirm positioning',
    '是否切换': 'Switch',
    '回馈激励': 'Rewards',
    '回馈展示': 'Rewards Mall',
    '附近': 'Nearby',
    '最新': 'Latest',
    '最热': 'Popular',
    '联盟活动': 'Alliance activities',
    '精品活动': 'Boutique activities',
    '询问': 'Inquiry',
    '请填写': 'Please fill in',

    '搜索项目/团队': 'Search',
    '搜索项目': 'Search',
    '搜索志愿团队': 'Search',
    '全国': 'China',
    '市': 'City',
    '城市': 'City',
    '当前城市': 'Current location',
    '志愿项目': 'Project',
    '志愿团队': 'Team',
    '正在加载': 'loading',
    '智能排序': 'Automatic sorting',
    '最新发布': 'Latest release',
    '距离最近': 'Nearest',
    '热门活动': 'Popular activities',
    '服务类型': 'Service type',
    '服务对象': 'Service object',
    '项目日期': 'Project date',
    '招募截止': 'Recruitment deadline',
    '服务时长': 'Volunteer hour',
    '搜索团队': 'Search',
    '团队类型': 'Team type',
    '党政机关': 'Party and government agency',
    '教育事业单位': 'Educational institution',
    '卫生事业单位': 'Health institution',
    '科技事业单位': 'Science and technology institution',
    '文化事业单位': 'Cultural institution',
    '社会福利事业单位': 'Social welfare institution',
    '其他事业单位': 'Other institution',
    '群团组织': 'Mass organizations',
    '居委会或村委会': 'Neighborhood committee or village committee',
    '国有企业': 'State-owned enterprise',
    '民营企业': 'Private enterprise',
    '社会团体': 'Social group',
    '社会服务机构': 'Social service agency',
    '基金会': 'Foundation',
    '外企': 'Foreign company',

    '所在区域': 'Your region',
    '目前还没有您已加入的团队哦': 'You haven’t joined any team',
    '目前还没有团队哦': 'No team',
    '目前还没有活动哦': 'No activity',
    '审核中': 'Review',
    '审核中，请稍后': 'Under review, please wait patiently',
    '时长': 'Volunteer hours',
    '志愿时长': 'Hours',
    '小时': 'H',
    '时': 'H',
    '成员': 'Members',
    '人': '',
    '活动日期': 'Activity date',
    '我的': 'My',
    '星币': 'Scores',
    '星币空格': ' Scores ',
    '明细': 'Details',
    '志愿回馈': 'Volunteer rewards',
    '请先登录': 'Login first',
    '兑换记录': 'Redeem record',
    '前往登录': 'Login',
    '目前还没有订单哦': 'No order',
    '目前还没有商品哦': 'No product',
    '元': 'yuan',
    '库存n件': '{{n}} pieces in stock',
    '件': 'piece',
    '至': '-',
    '发起方': 'Initiator',
    '支持方': 'Supporter',
    '商品简介': 'Product',
    '兑换该商品需要消耗n星币，您是否兑换': 'This product requires {{n}} points. Do you confirm the redeem',
    '兑换该商品需要消耗': 'This product requires',
    '您是否兑换吗': 'Do you confirm the redeem',
    '线下兑换日期': 'Product description',
    '已售罄': 'Sold out',
    '已达到兑换限制': 'Redemption limit reached',
    '返回积分商城首页': 'Return to the homepage of the Mall',
    '兑换失败': 'Redemption failed',
    '兑换成功': 'Redemption succeed',
    '支付金额': 'Pay',
    '积分': 'points',

    '立即兑换': 'Redeem now',
    '确认兑换': 'Confirm',
    '下单时间': 'Order time',
    '兑换时间': 'Redemption time',
    '未到兑换日期': 'The redemption date has not arrived',
    '确认已兑换': 'Confirm redemption',
    '兑换失败，商品已过兑换日期（不返还积分）': 'Redemption failed, for the product has passed the redemption date (your points will not be returned)',
    '兑换失败': 'Redemption failed',
    '兑换成功': 'Redemption succeed',
    '确认是否已兑换': 'Confirm whether it has been redeemed',
    '联系人姓名': 'Contact',
    '联系人电话': 'Mobile number',
    '志愿保障': 'Guarantee',
    '退出报名': 'Quit',
    '提示': 'Note',
    '登录提示': 'Note',
    '转发给好友': 'Forward to a friend',
    '分享到朋友圈': 'Share on my moments',
    '保存海报': 'Save',
    '您已被添加到黑名单，请联系客服': 'You have been blacklisted, please contact the customer service',
    '我要捐款': 'Donate',
    '我要报名': 'Sign up',
    '已录用人数': 'Number of volunteers recruited',
    '项目介绍': 'Introduction',
    '暂无介绍': 'No introduction',
    '收藏': 'Favorites',
    '收藏成功': 'Collect successfully',
    '取消收藏成功': 'Cancel successfully',
    '分享': 'Share',
    '项目详情': 'Project details',
    '项目社区': 'Project community',
    '确定要退出项目吗': 'Quit',
    '团队成员(人)': 'Team member(people)',
    '团队总时长(小时)': 'Total volunteer hours of team members(hours)',
    '团队口号': 'Team slogan',
    '团队详情': 'Team details',
    '团队成员': 'Team member',
    '我的收藏': 'My favorites',
    '上级团队': 'Superior team',
    '注册日期': 'Registration date',
    '团队管理': 'Management',
    '联系电话': 'Contact number',
    '团队地址': 'Address',
    '团队简介': 'Profile',
    '团队项目': 'Team project',
    '团队社区': 'Team community',
    '确定要退出团队吗': 'Quit',

    // 志愿圈
    '消息列表': 'Message',
    '发布动态': 'Post',
    '还没有动态信息': 'No update yet.',
    '只有登录的用户才能点赞和评论哦～': 'Likes and comments can be made after the user logs in～',
    '社区互动': 'Community moments',
    '请输入评论': 'Comment',
    '回复': 'Reply',
    '这一刻的想法': 'Thoughts at this moment (maximum 200 words)',
    '发表': 'Post',
    // 排行榜
    '年度榜': 'Annual list',
    '总榜': 'Overall list',
    '志愿排行': 'Ranking',
    'Ta的成就': 'Achievement',
    '年度时长': 'Annual volunteer hours',
    '总时长': 'Total volunteer hours',
    'Ta的项目': 'Projects',
    '获得': 'Get',
    '已获得时长': 'Volunteer hours',
    'Ta的团队': 'Team',

    '取消': 'Cancel',
    '确认': 'Confirm',
    '无': 'None',
    '删除': 'Delete',
    '选填': 'optional',
    '提交': 'Submit',
    '存在必填项，请完善后重新提交': 'Required information is not filled in, please complete and resubmit',

    '已结束': 'Registration is over',
    '我要加入': 'Join',
    '我要退出': 'Quit',
    '申请助养': 'Apply for sponsorship',
    '等待审核': 'Wait for review',
    '项目审核中': 'Under review',
    '进行中': 'Processing',
    '已满员': 'Fully recruited',

    '我发现了': 'I found',
    '我参与了': 'I joined',
    '团队': 'team',
    '项目': 'project',
    '累计获得': 'accumulated',
    '个服务时长': 'volunteer hours',
    '跟我一起做志愿服务吧': 'I have joined the team, join together',

    '我参与了"n"这个项目,累计获得x个服务时长,跟我一起做志愿服务吧': 'I\'ve participated in the project of "{{n}}",accumulated {{x}} Service hours. Join together~',

    '我发现了"n"这个项目,跟我一起做志愿服务吧': 'I\'ve just participated in the project of "{{n}}". Join together~',

    '我发现了"n"这个团队,跟我一起做志愿服务吧': 'I\'ve just joined the team of "{{n}}". Join together~',

    // 补卡
    '申请补卡成功': ' Applied for volunteer hours successfully',
    '申请服务时长': 'Application for volunteer hours',
    '申请补卡': 'Application after the activity',
    '参加项目': 'Join the project',
    '请选择': 'Please select',
    '参加活动地点': 'Activity location',
    '申请时长(小时)': 'Application hours',
    '申请说明(默认)': 'Application description (within 200 words)',
    '申请说明': 'Application description (within 200 words): Please specify the activity location (name of kindergarten, elementary school, etc.), number of beneficiaries (number of teachers, family members and students), and other relevant information about the activity.',
    '活动证明图片(默认)': 'Activity picture（optional）',
    '活动证明图片': 'Activity picture (such as student sign-in form, activity photo, group photo, etc.)',
    '还没有项目可以签到': 'No project',
    '快去加入项目吧': 'Join an activity',
    '浏览项目': 'Browse',
    '近3天待打卡项目': 'Projects to be checked in within three days',
    '签到打卡': 'Check in',
    '所有项目': 'All projects',
    '已进入签到地点范围': 'You’re in the sign-in location range',
    '查看签到地点': 'View the check-in location',
    '获取定位失败，请获取定位权限': 'Positioning failed, please obtain the permission',
    '定位中...': 'Positioning...',
    '打卡成功': 'Successfully checked in',
    '打卡': 'Check in',
    '签到': 'Check in',
    '时间': 'Time',
    '补卡': 'Application for volunteer hours',
    '待审': 'Wait for the review',
    '通过': 'Pass',
    '驳回': 'Reject',
    '打卡开始时间': 'Check-in starting time',
    '打卡截止时间': 'Check-in deadline',
    '签退时间': 'Check-out time',
    '签退打卡': 'Check out',
    '重新申请补卡': 'Apply for volunteer hours again',
    '预计可获得服务时长': 'Estimated volunteer hours',
    '获得服务时长': 'Volunteer hours obtained',
    '预计最多可获得服务时长': 'Estimated maximum volunteer hours',
    '未提审': 'Unsubmitted',
    '待打卡': 'To be checked in',
    '已通过': 'Pass',
    '审核中': 'Review',
    '被驳回': 'Reject',
    '已签到': 'Checked in',
    '待补卡': 'Wait for the application for volunteer hours',
    '目前还没有班次哟~': 'No activity',
    '近3天待打卡班次': 'To be checked in within three days',
    '所有班次': 'All activities',


    // 个人中心
    '未设置昵称': 'Username is not set',
    '未设置口号': 'Slogan is not set',
    '我的团队': 'My team',
    '我的项目': 'My project',
    '服务时长(center)': 'Volunteer hour',
    '星币(center)': 'points',
    '志愿': 'Volunteer',
    '个': 'piece',
    '个center': '',
    '小时center': '',
    '社区友好基金': 'Community shared fund',
    '我的志愿圈': 'Moments',
    '我的消息': 'My message',
    '个人资料': 'Personal information',
    '我的证书': 'My volunteer certificate',
    '我的家庭': 'My family',
    '服务中心': 'Service center',
    '平台介绍': 'Platform introduction',
    '使用帮助': 'User help',
    '客服中心': 'Customer service',
    '设置': 'Settings',
    '当前等级': 'Current level',
    '暂无等级': 'No level',
    '成长值': 'Points',
    '成长体系': 'Points system',
    '您可以通过更多志愿行为来获得成长值': 'You can earn points by providing volunteer services',
    '查看': 'View',
    '获取方法': 'Way to earn points',
    '查看成长值获得方法': 'View',
    '如何获得成长值': 'Way to earn points',
    '支出': ' Expenditure',
    '如何获得': 'Way to earn points',
    '下列操作可以帮你获得': 'The following operations can help you get',
    '下列操作可以帮你获得成长值': 'The following operations can help you earn points',
    '操作': 'Operate',
    '获得成长值': 'earn points',
    '我知道了': 'I see',  //按钮
    '退出登录': 'Log out',
    '修改密码': 'Revise the password',
    '新密码': 'New password',
    '确认修改': 'Confirm',
    '还没有消息哟': 'You have not received any messages',
    '目前还没有消息': 'You have not received any messages',
    '站内邮箱': 'Mailbox',
    '确认设置': 'Confirm',

    //
    '请填写': 'Fill in',
    '手机号': 'Mobile number',
    '发送': 'Send',
    '团队密码': 'Password',
    '确认密码': 'Confirm',
    '密码': 'Password',
    '请输入字母数字中文格式昵称': 'The username can only consist of numbers, letters and Chinese characters',
    '密码最少6位': 'The password must be at least 6 characters',
    '密码范围6-20位数字字母组成': 'The password can only consist of numbers and letters, and the length is 6-20 characters',
    '请输入合法的邮箱地址': 'Please enter a valid email address',
    '请输入正确的用户名': 'Please enter the correct username',
    '同一时间内不能多次点击': 'Cannot click multiple times at the same time',
    '上传头像(选填)': 'Upload profile picture (optional)',
    '昵称': 'Username',
    '图片码': 'Captcha',
    '验证码': 'Verification code',
    '注册': 'Register',
    '已有账号，前往登录': 'Already have an account, go to login',
    '志多星用户协议': 'User Agreement',
    '全部': 'All',
    '待录用': 'Pending',
    '已录用': 'Accepted',
    '请联系客服电话': 'Please call customer service',
    '确认提交': 'Confirm',
    '邮箱': 'E-mail',
    '暂无记录': 'No record',


    '关系': 'Relationship',
    '儿子': 'Son',
    '女儿': 'Daughter',
    '丈夫': 'Husband',
    '妻子': 'Wife',
    '母亲': 'Mother',
    '父亲': 'Father',
    '爷爷': 'Grandfather',
    '奶奶': 'Grandmother',
    '其他': 'Other',
    '添加': 'Confirm',
    '新建家庭成员': 'New family member',
    '姓名': 'Name',
    '证件类型': 'Type of certificate',
    '证件号码': 'ID number',
    '性别': 'Gender',
    '民族': 'Ethnicity',
    '现居住地址': 'Current address',
    '省份': 'Province',
    '区县': 'District/county',
    '详细地址': 'Detailed address',
    '街道': '街道',
    '出生日期': 'Date of birth',
    '请选择出生日期': 'Select your date of birth',
    '个人信息绑定': 'Binding your personal information',
    '员工号有误，请检查': 'Wrong Q number',
    '修改资料': 'Revise',
    '需要帮助': 'Need help',
    '申请成为实名注册志愿者': 'Real name authentication',
    '修改': 'Revise',
    '确定要修改成员信息吗': 'Revise the member information',
    '请输入中文姓名或英文姓名': 'Full name',
    '请输入中文姓名': 'Full Chinese name',
    '身份证输入不合法': 'Wrong ID number',


    '基本信息': 'Basic information',
    '头像': 'Profile',
    '账号': 'Account',
    '志愿者编号': 'Volunteer number',
    '个人擅长': 'Specialty',
    '关爱服务': 'Caring service',
    '国际服务': 'International service',
    '社区服务': 'Community service',
    '应急救援': 'Emergency rescue',
    '赛事服务': 'Tournament service',
    '医疗卫生': 'Medical care',
    '绿色环保': 'Environmental protection',
    '文化倡导': 'Cultural advocacy',
    '教育': 'Education',
    '助残': 'Assistance to the disabled',
    '助老': 'Assistance to the elderly',

    '志愿者口号': 'Slogan',
    '保存': 'Save',
    '实名认证信息': 'Real-name authentication information',

    '完善个人资料': 'Complete your information',
    '工作地点': 'Workplace',
    '男': 'Male',
    '女': 'Female',
    '未知': 'Unkown',
    '内地居民身份证':	'PRC Resident Identity Card',
    '香港居民身份证': 'Hong Kong Identity Card',
    '澳门居民身份证': 'Macau Identity Card',
    '台湾居民身份证': 'Taiwan Identity Card',
    '护照': 'Passport',

    '添加成员': 'Add member',
    '绑定家庭成员': 'Bind member',
    '家庭成员': 'Family member',
    '加载中': 'Loading',
    '志愿总时长': 'Total volunteer hours of members',
    '添加成员说明': 'Note: The added family member can log in with ID number and password',

    '参加的项目': 'Participated projects',
    '请选择申请项目': 'Select a project',
    '请选择申请班次': 'Choose time period',
    '请选择补卡时间': 'Apply for volunteer hours',
    '请选择签到时间': 'Check-in time',
    '请选择签退时间': 'Check-out time',
    '请输入详细说明': 'Application description',
    '补卡班次': 'Time',
    '打卡时间': 'Time',
    '签到补卡时间': 'Check-in time',
    '签退补卡时间': 'Check-out time',
    '工作证明图片': 'Activity picture',

    // 成就
    '生成图片失败，请重试': 'Failed to generate image, please try again',
    '累计服务时长': 'Accumulated volunteer hours',
    '次': '',
    '参加': 'join',
    '项目签到打卡': 'Check in',
    '项目累计服务时长': 'Accumulated volunteer hours',
    '服务时长已累计超过': 'The accumulated volunteer hours has exceeded',
    '快去晒成就吧': 'Show your achievements',
    '签到打卡次数已累计超过': 'The number of check-in has exceeded',
    '参加项目次数已累计超过': 'The number of participated projects has exceeded',
    '项目签到打卡次数已累计超过': 'The number of check-in has exceeded',

    '长按保存图片到手机': 'Long press to save the picture to the phone',
    '长按识别二维码 一起来做志愿者': 'Long press to identify the QR code to be volunteers together',
    '长按识别二维码': 'Long press to identify the QR code',
    '一起来做志愿者': 'to be volunteers together',
    '我发现了这个团队，跟我一起做志愿服务吧': 'I found this team, let\'s do volunteer service with me',

    '您已加入该团队': 'You have joined this team',
    '已成功申请，请耐心等待审核': 'You have applied successfully, please wait for review',
    '已成功申请': 'Applied successfully',
    '退出成功': 'Exit successfully',
    '目前还没有志愿项目哦': 'No project',
    '生成海报': 'Generate poster',


    '星币获取n': 'Way to earn {{n}}',
    '星币支出n': '{{n}} expenditure',
    '查看星币获取方法n': 'Way to earn {{n}}',
    '我的星币明细n': 'My {{n}} detail',
    '如何获得星币n': 'Way to earn {{n}}',
    '获得星币n': 'Earn {{n}}',
    '我的星币n': 'My {{n}}',
    'n志愿星币m': '{{n}} {{m}}',
    '志愿center': 'My',
    '下列操作可以帮你获得n': 'The following operations can help you get {{n}}',
    '￥n元': '￥{{n}}',
    '获得n': 'get {{n}}',
    'n个': 'Piece',
    'n人': '',
    '确定': 'Confirm',
    '文明点亮你我，志愿感动社会': 'Volunteer together, contribute selfless love and unlimited hope to society',

    'person-entry': 'page-entry-person-btn-en',
    'person-entry-bmw': 'page-entry-person-btn-bmw-en',

    'team-login-entry': 'page-entry-team-btn-default-en',
    'team-login-entry-bmw': 'page-entry-team-btn-bmw-en',

    'team-register-entry': 'page-entry-team-btn-default-en',
    'team-register-entry-bmw': 'page-entry-team-btn-default-bmw-en',


    'project-status-employed': 'project-status-employed-en',
    'project-status-employed-wait': 'project-status-employed-wait-en',
    'project-status-employed-reject': 'project-status-employed-reject-en',
    'project-status-employed-end': 'project-status-employed-end-en',
    'project-status-recruit': 'project-status-recruit-en',
    'project-status-full': 'project-status-full-en',
    'project-status-progress': 'project-status-progress-en',
    'project-status-end': 'project-status-end-en',
    'project-status-end-time': 'project-status-end-time-en',

    '发送成功': 'Sent successfully',
    'backhome': '/images/my/backhome-en.png',
    '请求失败': 'Failed',

    // 个人消息
    '您申请的项目已被录用，请准时参加该活动n': 'Your application to join 《{{n}}》 have been accepted, please join on time',
    '您申请加入项目《n》未通过审核': 'Your application to join 《{{n}}》 has been rejected',
    '您已成功加入《n》，与团队小伙伴一起来做公益吧': 'You have successfully joined  《{{n}}》，let\'s do public welfare together with your team partners',
    '您申请参加的团队《n》审核不通过，去看看其他更合适自己的团队吧': 'You have failed to pass the review of joining the 《{{n}}》. Please view the list to join other team',
  },
}
